# Generated by Django 6.0.2 on 2026-05-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_readd_player_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='account_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='account_raw',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mmr_raw',
        ),
        migrations.RemoveField(
            model_name='player',
            name='region',
        ),
    ]
